version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
