name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "Workspace directory: \"$GITHUB_WORKSPACE\""
          echo "Current directory:"
          ls
          echo "Directory contents:"
          ls -la "$GITHUB_WORKSPACE"
      
      - name: Set up environment
        run: |
          # Store the workspace path in a file to avoid space issues
          echo "$GITHUB_WORKSPACE" > ~/.workspace_path
          WORKSPACE_PATH=$(cat ~/.workspace_path)
          cd "$WORKSPACE_PATH"
          echo "Changed to workspace directory: $PWD"
      
      - name: Build API
        run: |
          WORKSPACE_PATH=$(cat ~/.workspace_path)
          cd "$WORKSPACE_PATH"
          make build
      
      - name: Run tests
        run: |
          WORKSPACE_PATH=$(cat ~/.workspace_path)
          cd "$WORKSPACE_PATH"
          make test
      
      - name: Run linting
        run: |
          WORKSPACE_PATH=$(cat ~/.workspace_path)
          cd "$WORKSPACE_PATH"
          make lint
      
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and push Docker image
        run: |
          WORKSPACE_PATH=$(cat ~/.workspace_path)
          cd "$WORKSPACE_PATH"  
          
          # Get the short SHA of the commit
          SHA=$(git rev-parse --short HEAD)
          
          # Build the image with both latest and SHA tags
          docker build -t "${{ secrets.DOCKER_USERNAME }}/student-api:latest" .
          docker build -t "${{ secrets.DOCKER_USERNAME }}/student-api:${SHA}" .
          
          # Push both tags
          docker push "${{ secrets.DOCKER_USERNAME }}/student-api:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/student-api:${SHA}"
