name: CI Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'code/**'
  pull_request:
    paths:
      - 'code/**'

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "Workspace directory: \"$GITHUB_WORKSPACE\""
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la "$GITHUB_WORKSPACE"

      - name: Build API
        run: |
          cd "$GITHUB_WORKSPACE"
          make build
      
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE"
          make test
      
      - name: Run linting
        run: |
          cd "$GITHUB_WORKSPACE"
          make lint
      
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and push Docker image
        run: |
          cd "$GITHUB_WORKSPACE"
          
          # Get the short SHA of the commit
          SHA=$(git rev-parse --short HEAD)
          
          # Build the image with both latest and SHA tags
          docker build -t "${{ secrets.DOCKER_USERNAME }}/student-api:latest" .
          docker build -t "${{ secrets.DOCKER_USERNAME }}/student-api:${SHA}" .
          
          # Push both tags
          docker push "${{ secrets.DOCKER_USERNAME }}/student-api:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/student-api:${SHA}"
