name: CI Pipeline

on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger on push to specific paths
  push:
    paths:
      - 'code/**'
      
  # Trigger on pull request to specific paths
  pull_request:
    paths:
      - 'code/**'

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build API
        run: make build
      
      - name: Run tests
        run: make test
      
      - name: Run linting
        run: make lint
      
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and push Docker image
        run: |
          # Get the short SHA of the commit
          SHA=$(git rev-parse --short HEAD)
          
          # Build the image with both latest and SHA tags
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-api:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-api:${SHA} .
          
          # Push both tags
          docker push ${{ secrets.DOCKER_USERNAME }}/student-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/student-api:${SHA}